# general settings
name: Deblur_3Dconv_add
model_type: VideoRecurrentModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: REDS
    type: REDSRecurrentDataset
    dataroot_gt: /media/xbm/data/VideoDeblur_Dataset/REDS/sharp/train_sharp
    dataroot_lq: /media/xbm/data/VideoDeblur_Dataset/REDS/blur/train_blur
    meta_info_file: basicsr/data/meta_info/meta_info_REDS_GT.txt
    val_partition: REDS4  # set to 'official' when use the official validation partition
    test_mode: False
    io_backend:
      type: disk

    num_frame: 5
    gt_size: 256
    interval_list: [1]
    random_reverse: false
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 2
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 200
    prefetch_mode: ~

  val:
    name: REDS4
    type: VideoRecurrentTestDataset
    dataroot_gt: /media/xbm/data/VideoDeblur_Dataset/REDS4_crop20/sharp
    dataroot_lq: /media/xbm/data/VideoDeblur_Dataset/REDS4_crop20/blur

    cache_data: true
    io_backend:
      type: disk

    num_frame: -1  # not needed

# network structures
network_g:
  type: Deblur
  num_feat: 64
  num_block: 3

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [300000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 300000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: 1000
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: 1000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
